### ISSUE TITLE
Week 2 HW Comments

### ISSUE THREAD

**Issue by kevinmccartney** [eewhy/js-app-dev-week2#1]
Hey Ey! Great job on this. Two small things -

1. On `gratuity.js`, why don't you move the code above project assignment (everything above line 11) to another file? If code isn't related to the problem you're trying to solve, it's good to move it somewhere else so it's not confusing when you're looking back it.
2. On `rockPaperScissorsRevisted.js`, be sure to log out the winner of the game when a player has reached 3 wins.

**Comment by eewhy** [comment]
Completed :)

**Comment by kevinmccartney** [comment]
Looks great!
